l=[10,20,30,40,50,60,70]
print(l[0:5:2]) #step+ve,index+ve-- [start,end,step]
print(l[:5:1])#step+ve, index+ve---[end,step]
print(l[::1])#step+ve,index-+ve---[step]
print(l[-5:-1:2])#step+ve,index-ve--[start,end,step]
print(l[:-1:1])#step+ve,index-ve--[end,step]
print(l[-1:])#step+ve,index-ve--[start]
print(l[-0:-5:-1])#step-ve,index-ve--[start,end,step]
print(l[-5::-1])#step-ve,index-ve--[start,step]
print(l[::-1])#step-ve,index-ve--[step]
print(l[5:5:-1])#step-ve, index+ve--[start,end,step]
print(l[5::-1])#step-ve, index+ve--[start,step]
print(l[:4:-1])#step-ve, index+ve--[end,step]